// SPDX-License-Identifier: Apache-2.0
// Model-independent block-forward-substitution-v1 graph, frozen from Indexed's
// private_ane reference at chunk64/block8/head16/FP16/query-scale4096.
// Source MIL SHA-256: e39e382e3e29174939179551b20e242290c325529515788899079b8d8c31d0e4
// Operations contain no model weights or user inputs.
import Foundation

extension PrivateGDNGraph {
    static let operations: [(String, String, String, String?)] = [
        ("lower_log_terms", "matmul", "lower_inclusive", "log_decay_diagonal"),
        ("prefix_log_rows", "matmul", "lower_log_terms", "ones"),
        ("upper_log_terms", "matmul", "log_decay_diagonal", "upper_inclusive"),
        ("prefix_log_columns", "matmul", "ones", "upper_log_terms"),
        ("negative_prefix_columns", "mul", "prefix_log_columns", "negative_ones"),
        ("pair_log_difference", "add", "prefix_log_rows", "negative_prefix_columns"),
        ("masked_pair_log_difference", "mul", "pair_log_difference", "lower_inclusive"),
        ("pair_decay", "exp", "masked_pair_log_difference", nil),
        ("negative_strict_decay", "mul", "pair_decay", "negative_strict_lower"),
        ("inclusive_decay", "mul", "pair_decay", "lower_inclusive"),
        ("final_log", "matmul", "last_row_selector", "prefix_log_rows"),
        ("final_log_difference", "add", "final_log", "negative_prefix_columns"),
        ("final_decay_columns", "exp", "final_log_difference", nil),
        ("terminal_decay", "exp", "final_log", nil),
        ("prefix_decay_rows", "exp", "prefix_log_rows", nil),
        ("key_gram", "matmul", "k", "kt"),
        ("negative_lower_gram", "mul", "key_gram", "negative_strict_decay"),
        ("recurrence", "mul", "negative_lower_gram", "beta"),
        ("state_read", "matmul", "k", "state"),
        ("decayed_state_read", "mul", "state_read", "prefix_decay_rows"),
        ("negative_state_read", "mul", "decayed_state_read", "negative_ones"),
        ("residual", "add", "v", "negative_state_read"),
        ("right_hand_side", "mul", "residual", "beta"),
        ("solve_local_recurrence", "mul", "recurrence", "solve_block_diagonal"),
        ("solve_cross_recurrence", "mul", "recurrence", "solve_block_strict_lower"),
        ("solve_local_inverse_0", "add", "identity", "solve_local_recurrence"),
        ("solve_local_power_0_copy", "mul", "solve_local_recurrence", "ones"),
        ("solve_local_power_1", "matmul", "solve_local_recurrence", "solve_local_power_0_copy"),
        ("solve_local_factor_1", "add", "identity", "solve_local_power_1"),
        ("solve_local_inverse_1", "matmul", "solve_local_inverse_0", "solve_local_factor_1"),
        ("solve_local_power_1_copy", "mul", "solve_local_power_1", "ones"),
        ("solve_local_power_2", "matmul", "solve_local_power_1", "solve_local_power_1_copy"),
        ("solve_local_factor_2", "add", "identity", "solve_local_power_2"),
        ("solve_local_inverse_2", "matmul", "solve_local_inverse_1", "solve_local_factor_2"),
        ("solve_local_rhs", "matmul", "solve_local_inverse_2", "right_hand_side"),
        ("solve_block_transfer", "matmul", "solve_local_inverse_2", "solve_cross_recurrence"),
        ("solve_solution_0", "mul", "solve_local_rhs", "solve_rows_0"),
        ("solve_propagated_1", "matmul", "solve_block_transfer", "solve_solution_0"),
        ("solve_candidate_1", "add", "solve_local_rhs", "solve_propagated_1"),
        ("solve_selected_1", "mul", "solve_candidate_1", "solve_rows_1"),
        ("solve_solution_1", "add", "solve_solution_0", "solve_selected_1"),
        ("solve_propagated_2", "matmul", "solve_block_transfer", "solve_solution_1"),
        ("solve_candidate_2", "add", "solve_local_rhs", "solve_propagated_2"),
        ("solve_selected_2", "mul", "solve_candidate_2", "solve_rows_2"),
        ("solve_solution_2", "add", "solve_solution_1", "solve_selected_2"),
        ("solve_propagated_3", "matmul", "solve_block_transfer", "solve_solution_2"),
        ("solve_candidate_3", "add", "solve_local_rhs", "solve_propagated_3"),
        ("solve_selected_3", "mul", "solve_candidate_3", "solve_rows_3"),
        ("solve_solution_3", "add", "solve_solution_2", "solve_selected_3"),
        ("solve_propagated_4", "matmul", "solve_block_transfer", "solve_solution_3"),
        ("solve_candidate_4", "add", "solve_local_rhs", "solve_propagated_4"),
        ("solve_selected_4", "mul", "solve_candidate_4", "solve_rows_4"),
        ("solve_solution_4", "add", "solve_solution_3", "solve_selected_4"),
        ("solve_propagated_5", "matmul", "solve_block_transfer", "solve_solution_4"),
        ("solve_candidate_5", "add", "solve_local_rhs", "solve_propagated_5"),
        ("solve_selected_5", "mul", "solve_candidate_5", "solve_rows_5"),
        ("solve_solution_5", "add", "solve_solution_4", "solve_selected_5"),
        ("solve_propagated_6", "matmul", "solve_block_transfer", "solve_solution_5"),
        ("solve_candidate_6", "add", "solve_local_rhs", "solve_propagated_6"),
        ("solve_selected_6", "mul", "solve_candidate_6", "solve_rows_6"),
        ("solve_solution_6", "add", "solve_solution_5", "solve_selected_6"),
        ("solve_propagated_7", "matmul", "solve_block_transfer", "solve_solution_6"),
        ("solve_candidate_7", "add", "solve_local_rhs", "solve_propagated_7"),
        ("solve_selected_7", "mul", "solve_candidate_7", "solve_rows_7"),
        ("update_values", "add", "solve_solution_6", "solve_selected_7"),
        ("query_key", "matmul", "q", "kt"),
        ("causal_query_key", "mul", "query_key", "inclusive_decay"),
        ("state_output", "matmul", "q", "state"),
        ("decayed_state_output", "mul", "state_output", "prefix_decay_rows"),
        ("update_output", "matmul", "causal_query_key", "update_values"),
        ("scaled_output", "add", "decayed_state_output", "update_output"),
        ("decayed_key_transpose", "mul", "kt", "final_decay_columns"),
        ("state_update", "matmul", "decayed_key_transpose", "update_values"),
        ("decayed_state", "mul", "state", "terminal_decay"),
        ("final_state", "add", "decayed_state", "state_update"),
        ("output", "mul", "scaled_output", "query_inverse_scale"),
    ]
}
